services:
  web:
    image: dev_ops_start_project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: dev_ops_start_project_container
    environment:
      NODE_ENV: development
